### ISSUE TITLE
Add a code property to each ErrorDetail object

### ISSUE THREAD

**Issue by iamdtang** [Edgio/hyperion#15]
I propose we add `code` to each `ErrorDetail` object. Say you have a name attribute. It can fail for more than reason. For example, it has a required validation rule and a maximum character length validation rule. I'd like to define separate error messages for these on the frontend. In order to map an `ErrorDetail` object to the specific error message defined on the frontend, I would need some kind of code like `required_attribute` or `invalid_length`. JSON:API supports this via a `code` property: https://jsonapi.org/format/#error-objects

For example, if a client makes a request without `name`, the response might look like this:

```json
{
  "@type": "Error",
  "code": "invalid_request",
  "title": "...",
  "details": [
    {
      "@type": "ErrorDetail",
      "description": "...",
      "source": "/name",
      "code": "required"
    }
  ]
}
```

If a client makes a request with `name` but it is too long, the response might look like this:

```json
{
  "@type": "Error",
  "code": "invalid_request",
  "title": "...",
  "details": [
    {
      "@type": "ErrorDetail",
      "description": "...",
      "source": "/name",
      "code": "too_long"
    }
  ]
}
```

The frontend can then key off of `required` or `too_long` to display the proper error message defined on the frontend.

The alternative is for frontends to rely on `description` provided by the backend.

**Comment by thehelix112** [comment]
This makes sense to me. I think code should be optional in the error detail as there might not always be a different code than the main object and we don't wanna require redundancy. What do you think?

**Comment by iamdtang** [comment]
@thehelix112 ya that makes sense

**Comment by ardiesaeidi** [comment]
Closing since this issue was resolved.
