### ISSUE TITLE
Appendix / lookup endpoints consolidation path

### ISSUE THREAD

**Issue by teehill** [Edgio/hyperion#23]
An idea was floated during SSL Automation API review to have static / lookup endpoints be grouped under a path. Often 10+ endpoints that serve static lookup data for UIs to consume, might be nice to have a convention on grouping them in a way so they don't clutter up the service root path, leaving it for the more actionable endpoints.

I think there was a suggestion of `/appendix`.

**Comment by jsernaque** [comment]
Grouping ancillary endpoints into a single bucket (e.g., `/appendix/`) makes for an unnecessarily long URL and adds a random URL segment that devs will need to remember. For example, if you want to get country codes, you have to remember that this is a special endpoint that has been segregated from the rest and that it can be found under `/appendix`. Alternatively, you would only have to remember that the endpoint is `/country-codes`

**Comment by teehill** [comment]
Discoverability would be handled by the root endpoint's "directory listing". Adding an unnecessary segment into the URL isn't best case I agree. Sounds like the organizational benefits of separating lookup endpoints probably doesn't outweigh the confusion or added characters in the URL.
